-- Money Flow: authenticated database setup
-- Run this file in Supabase Dashboard > SQL Editor for a new project.
--
-- This file is the BASELINE. Changes made after the baseline belong in
-- supabase/migrations/ as their own timestamped file (see the README there),
-- and should also be folded back into this file so a brand-new project still
-- gets the complete, current schema in one run.
--
-- Existing projects must first assign every legacy row to a real auth.users UUID
-- before `alter column user_id set not null` can succeed. Back up the table first.
-- Never replace these owner policies with anonymous `using (true)` policies.

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  description text not null check (char_length(description) between 1 and 120),
  amount numeric(12, 2) not null check (amount > 0),
  type text not null check (type in ('income', 'expense')),
  category text,
  transaction_date date not null default current_date,
  created_at timestamptz not null default now()
);

-- Upgrade support for projects created before categories and ownership were added.
alter table public.transactions
add column if not exists category text;

alter table public.transactions
add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.transactions
alter column user_id set default auth.uid();

-- Declarative upper bound so a bad amount is rejected even if the trigger below
-- is ever dropped. Matches AMOUNT_MAX in src/schemas/transaction.schema.ts.
alter table public.transactions
drop constraint if exists transactions_amount_max_check;

alter table public.transactions
add constraint transactions_amount_max_check check (amount <= 999999999);

-- This intentionally fails if legacy rows have not been assigned to an owner.
alter table public.transactions
alter column user_id set not null;

alter table public.transactions enable row level security;

-- Remove the retired anonymous policies.
drop policy if exists "Public can read transactions" on public.transactions;
drop policy if exists "Public can create transactions" on public.transactions;
drop policy if exists "Public can update transactions" on public.transactions;
drop policy if exists "Public can delete transactions" on public.transactions;

-- Keep this script safe to run again.
drop policy if exists "Users can read own transactions" on public.transactions;
drop policy if exists "Users can create own transactions" on public.transactions;
drop policy if exists "Users can update own transactions" on public.transactions;
drop policy if exists "Users can delete own transactions" on public.transactions;

revoke select, insert, update, delete on public.transactions from anon;
revoke usage, select on sequence public.transactions_id_seq from anon;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.transactions to authenticated;
grant usage, select on sequence public.transactions_id_seq to authenticated;

create policy "Users can read own transactions"
on public.transactions for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own transactions"
on public.transactions for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own transactions"
on public.transactions for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own transactions"
on public.transactions for delete
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists transactions_user_id_idx
on public.transactions (user_id);

create index if not exists transactions_date_created_idx
on public.transactions (transaction_date desc, created_at desc);

-- Server-side validation. RLS decides *who* may write a row; this trigger decides
-- whether the row itself is sane, so a hand-rolled API call cannot store garbage
-- that the client form would have rejected. Keep the limits in sync with
-- src/schemas/transaction.schema.ts.
create or replace function public.transactions_validate()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  -- Never let a caller write rows on someone else's behalf, even by accident.
  if new.user_id is null then
    new.user_id := auth.uid();
  end if;

  if new.user_id <> auth.uid() then
    raise exception 'user_id must match the authenticated user'
      using errcode = '42501';
  end if;

  new.description := btrim(new.description);

  if new.description is null or char_length(new.description) = 0 then
    raise exception 'description must not be empty'
      using errcode = '23514';
  end if;

  if char_length(new.description) > 120 then
    raise exception 'description must be 120 characters or fewer'
      using errcode = '23514';
  end if;

  -- Strip control characters that only ever arrive from a scripted client.
  new.description := regexp_replace(new.description, '[\u0000-\u001f\u007f]', '', 'g');

  if new.amount is null or new.amount <= 0 then
    raise exception 'amount must be greater than 0'
      using errcode = '23514';
  end if;

  if new.amount > 999999999 then
    raise exception 'amount exceeds the allowed maximum'
      using errcode = '23514';
  end if;

  new.amount := round(new.amount, 2);

  if new.type not in ('income', 'expense') then
    raise exception 'type must be income or expense'
      using errcode = '23514';
  end if;

  if new.category is not null then
    new.category := btrim(new.category);
    if char_length(new.category) = 0 then
      new.category := null;
    elsif char_length(new.category) > 60 then
      raise exception 'category must be 60 characters or fewer'
        using errcode = '23514';
    end if;
  end if;

  if new.transaction_date is null then
    raise exception 'transaction_date is required'
      using errcode = '23514';
  end if;

  -- Loose bounds on purpose: back-dating is a real use case, but a date centuries
  -- away is always a bug or an abuse attempt.
  if new.transaction_date < date '1970-01-01'
     or new.transaction_date > (current_date + interval '1 year') then
    raise exception 'transaction_date is out of the allowed range'
      using errcode = '23514';
  end if;

  -- created_at is a server-owned audit field; ignore whatever the client sent.
  if tg_op = 'INSERT' then
    new.created_at := now();
  else
    new.created_at := old.created_at;
    new.id := old.id;
  end if;

  return new;
end;
$$;

drop trigger if exists transactions_validate_trg on public.transactions;

create trigger transactions_validate_trg
before insert or update on public.transactions
for each row execute function public.transactions_validate();

-- Remove the retired monthly budget feature when upgrading an existing project.
drop function if exists public.replace_monthly_budgets(date, jsonb);
drop table if exists public.monthly_budgets;

-- Achievements: one row per badge a user has unlocked.
-- Badge definitions live in the client (src/types/achievement.ts); only the
-- unlocked state is stored here, so adding a badge needs no migration.
create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  badge_id text not null check (char_length(badge_id) between 1 and 60),
  unlocked_at timestamptz not null default now(),
  unique (user_id, badge_id)
);

alter table public.user_achievements enable row level security;

-- Keep this script safe to run again.
drop policy if exists "Users can read own achievements" on public.user_achievements;
drop policy if exists "Users can create own achievements" on public.user_achievements;
drop policy if exists "Users can delete own achievements" on public.user_achievements;

revoke select, insert, update, delete on public.user_achievements from anon;
revoke usage, select on sequence public.user_achievements_id_seq from anon;

-- No update grant: an unlocked badge is append-only from the client.
grant select, insert, delete on public.user_achievements to authenticated;
grant usage, select on sequence public.user_achievements_id_seq to authenticated;

create policy "Users can read own achievements"
on public.user_achievements for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own achievements"
on public.user_achievements for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- Needed so "reset all data" can clear a user's own badges.
create policy "Users can delete own achievements"
on public.user_achievements for delete
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists user_achievements_user_id_idx
on public.user_achievements (user_id);

-- Same defence in depth as transactions: ownership and the timestamp are decided
-- by the server, not by whatever the client happens to send.
create or replace function public.user_achievements_validate()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  if new.user_id is null then
    new.user_id := auth.uid();
  end if;

  if new.user_id <> auth.uid() then
    raise exception 'user_id must match the authenticated user'
      using errcode = '42501';
  end if;

  new.badge_id := btrim(new.badge_id);

  if new.badge_id is null or char_length(new.badge_id) = 0 then
    raise exception 'badge_id must not be empty'
      using errcode = '23514';
  end if;

  new.unlocked_at := now();

  return new;
end;
$$;

drop trigger if exists user_achievements_validate_trg on public.user_achievements;

create trigger user_achievements_validate_trg
before insert on public.user_achievements
for each row execute function public.user_achievements_validate();
