-- Money Flow: authenticated database setup
-- Run this file in Supabase Dashboard > SQL Editor for a new project.
--
-- Existing projects must first assign every legacy row to a real auth.users UUID
-- before `alter column user_id set not null` can succeed. Back up the table first.
-- Never replace these owner policies with anonymous `using (true)` policies.

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  description text not null check (char_length(description) between 1 and 120),
  amount numeric(12, 2) not null check (amount > 0),
  type text not null check (type in ('income', 'expense')),
  category text,
  transaction_date date not null default current_date,
  created_at timestamptz not null default now()
);

-- Upgrade support for projects created before categories and ownership were added.
alter table public.transactions
add column if not exists category text;

alter table public.transactions
add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.transactions
alter column user_id set default auth.uid();

-- This intentionally fails if legacy rows have not been assigned to an owner.
alter table public.transactions
alter column user_id set not null;

alter table public.transactions enable row level security;

-- Remove the retired anonymous policies.
drop policy if exists "Public can read transactions" on public.transactions;
drop policy if exists "Public can create transactions" on public.transactions;
drop policy if exists "Public can update transactions" on public.transactions;
drop policy if exists "Public can delete transactions" on public.transactions;

-- Keep this script safe to run again.
drop policy if exists "Users can read own transactions" on public.transactions;
drop policy if exists "Users can create own transactions" on public.transactions;
drop policy if exists "Users can update own transactions" on public.transactions;
drop policy if exists "Users can delete own transactions" on public.transactions;

revoke select, insert, update, delete on public.transactions from anon;
revoke usage, select on sequence public.transactions_id_seq from anon;

grant usage on schema public to authenticated;
grant select, insert, update, delete on public.transactions to authenticated;
grant usage, select on sequence public.transactions_id_seq to authenticated;

create policy "Users can read own transactions"
on public.transactions for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own transactions"
on public.transactions for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own transactions"
on public.transactions for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete own transactions"
on public.transactions for delete
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists transactions_user_id_idx
on public.transactions (user_id);

create index if not exists transactions_date_created_idx
on public.transactions (transaction_date desc, created_at desc);

-- Remove the retired monthly budget feature when upgrading an existing project.
drop function if exists public.replace_monthly_budgets(date, jsonb);
drop table if exists public.monthly_budgets;

-- Achievements: one row per badge a user has unlocked.
-- Badge definitions live in the client (src/types/achievement.ts); only the
-- unlocked state is stored here, so adding a badge needs no migration.
create table if not exists public.user_achievements (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  badge_id text not null check (char_length(badge_id) between 1 and 60),
  unlocked_at timestamptz not null default now(),
  unique (user_id, badge_id)
);

alter table public.user_achievements enable row level security;

-- Keep this script safe to run again.
drop policy if exists "Users can read own achievements" on public.user_achievements;
drop policy if exists "Users can create own achievements" on public.user_achievements;
drop policy if exists "Users can delete own achievements" on public.user_achievements;

revoke select, insert, update, delete on public.user_achievements from anon;
revoke usage, select on sequence public.user_achievements_id_seq from anon;

-- No update grant: an unlocked badge is append-only from the client.
grant select, insert, delete on public.user_achievements to authenticated;
grant usage, select on sequence public.user_achievements_id_seq to authenticated;

create policy "Users can read own achievements"
on public.user_achievements for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own achievements"
on public.user_achievements for insert
to authenticated
with check ((select auth.uid()) = user_id);

-- Needed so "reset all data" can clear a user's own badges.
create policy "Users can delete own achievements"
on public.user_achievements for delete
to authenticated
using ((select auth.uid()) = user_id);

create index if not exists user_achievements_user_id_idx
on public.user_achievements (user_id);
