-- Money Flow: initial database setup
-- Run this file in Supabase Dashboard > SQL Editor.
-- It is safe to run again when this project adds a new column or policy.
--
-- Learning-project security note:
-- These policies allow anyone with the public anon key to read and change all rows.
-- Add Supabase Auth and owner-based policies before storing real or production data.

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  description text not null check (char_length(description) between 1 and 120),
  amount numeric(12, 2) not null check (amount > 0),
  type text not null check (type in ('income', 'expense')),
  category text,
  transaction_date date not null default current_date,
  created_at timestamptz not null default now()
);

-- Safe to run again for projects created before categories were added.
alter table public.transactions
add column if not exists category text;

alter table public.transactions enable row level security;

drop policy if exists "Public can read transactions" on public.transactions;
create policy "Public can read transactions"
on public.transactions for select
to anon
using (true);

drop policy if exists "Public can create transactions" on public.transactions;
create policy "Public can create transactions"
on public.transactions for insert
to anon
with check (true);

drop policy if exists "Public can update transactions" on public.transactions;
create policy "Public can update transactions"
on public.transactions for update
to anon
using (true)
with check (true);

drop policy if exists "Public can delete transactions" on public.transactions;
create policy "Public can delete transactions"
on public.transactions for delete
to anon
using (true);

grant usage on schema public to anon;
grant select, insert, update, delete on public.transactions to anon;
grant usage, select on sequence public.transactions_id_seq to anon;

create index if not exists transactions_date_created_idx
on public.transactions (transaction_date desc, created_at desc);

-- Remove the retired monthly budget feature when upgrading an existing project.
drop function if exists public.replace_monthly_budgets(date, jsonb);
drop table if exists public.monthly_budgets;
